export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const FETCH_INITIAL_PRODUCTS = 'FETCH_INITIAL_PRODUCTS';
export const SET_INITIAL_PRODUCTS = 'SET_INITIAL_PRODUCTS';

export const ADD_NEW_PRODUCT_TO_ARCHIVE = 'ADD_NEW_PRODUCT_TO_ARCHIVE';
export const RESTORE_ARCHIVED_PRODUCT = 'RESTORE_ARCHIVED_PRODUCT';

export const ADD_PRODUCT_COMPLETE = 'ADD_PRODUCT_COMPLETE';
export const ADD_PRODUCT_COMPLETE_RESET = 'ADD_PRODUCT_COMPLETE_RESET';
export const DELETE_COMPLETE_RESET = 'DELETE_COMPLETE_RESET';
export const ADD_TO_ARCHIVE_COMPLETE_RESET = 'ADD_TO_ARCHIVE_COMPLETE_RESET';
export const RESTORE_FROM_ARCHIVE_COMPLETE_RESET = 'RESTORE_FROM_ARCHIVE_COMPLETE_RESET';
