export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const FETCH_INITIAL_PRODUCTS = 'FETCH_INITIAL_PRODUCTS';
export const SET_INITIAL_PRODUCTS = 'SET_INITIAL_PRODUCTS';

export const REPORT_ERROR = 'REPORT_ERROR';